## Import the Dependencies

In [1]:
import pandas as pd
import numpy as np
import nltk                # natural language tool kit
import matplotlib.pyplot as plt

## Data collection and processing

In [2]:
news_data = pd.read_csv(r"C:\Users\lenovo\Python data\Projects\Fake News Prediction\train.csv")

In [3]:
news_data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
# Checking the number of rows and columns
news_data.shape

(20800, 5)

In [7]:
# Check the number of missing values in each columns
news_data.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [6]:
# replacing the null values with empty string
news_data = news_data.fillna('')

In [8]:
# merging the author name and news title
news_data['content'] = news_data['author']+' '+news_data['title']

In [12]:
news_data.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

                                             content  
0  Darrell Lucus House Dem Aide: We Didn’t Even S...  
1  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...  
2  Consortiumnews.com Why the Truth Might Get You...  
3  Jessica Purkiss 15 Civilians Killed In Single ...  
4  Howard Portnoy Iranian woman jailed for fictio...

In [14]:
news_data = news_data.iloc[:,-2:]
news_data.head()

label                                            content
0      1  Darrell Lucus House Dem Aide: We Didn’t Even S...
1      0  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2      1  Consortiumnews.com Why the Truth Might Get You...
3      1  Jessica Purkiss 15 Civilians Killed In Single ...
4      1  Howard Portnoy Iranian woman jailed for fictio...

In [15]:
news_data.label.value_counts()

1    10413
0    10387
Name: label, dtype: int64

In [16]:
news_data.content = news_data.content.str.lower()
news_data.content

0        darrell lucus house dem aide: we didn’t even s...
1        daniel j. flynn flynn: hillary clinton, big wo...
2        consortiumnews.com why the truth might get you...
3        jessica purkiss 15 civilians killed in single ...
4        howard portnoy iranian woman jailed for fictio...
                               ...                        
20795    jerome hudson rapper t.i.: trump a ’poster chi...
20796    benjamin hoffman n.f.l. playoffs: schedule, ma...
20797    michael j. de la merced and rachel abrams macy...
20798    alex ansary nato, russia to hold parallel exer...
20799              david swanson what keeps the f-35 alive
Name: content, Length: 20800, dtype: object

In [17]:
from nltk.corpus import stopwords

In [18]:
# We are just check the stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [19]:
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [20]:
import string

In [21]:
string.punctuation # leter we will remove them also

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [22]:
# we will remove the stop word, punctuation and 
# tokenization (assign id to each word)
# create a tdm
# then do sampling, 
# build the model, 
# do the prediction


In [23]:
def text_process(mess):            ### creating a function
    """                                                        ## a docstring
    1. remove the punctuation
    2. remove the stopwords
    3. return the list of clean textwords
    
    """
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = "".join(nopunc)
    
    return [ word for word in nopunc.split() if word not in stopwords.words("english")]


In [24]:
from sklearn.feature_extraction.text import CountVectorizer
# it is used to give count for each unique word

In [25]:
after_trans = CountVectorizer(analyzer=text_process).fit(news_data['content'])

In [26]:
after_trans.vocabulary_

{'darrell': 6556,
 'lucus': 15039,
 'house': 12161,
 'dem': 6885,
 'aide': 1244,
 'didn’t': 7248,
 'even': 8842,
 'see': 22247,
 'comey’s': 5427,
 'letter': 14591,
 'jason': 13329,
 'chaffetz': 4662,
 'tweeted': 25833,
 'daniel': 6514,
 'j': 13251,
 'flynn': 9892,
 'hillary': 11861,
 'clinton': 5169,
 'big': 3160,
 'woman': 27500,
 'campus': 4251,
 'breitbart': 3757,
 'consortiumnewscom': 5732,
 'truth': 25722,
 'might': 16038,
 'get': 10617,
 'fired': 9698,
 'jessica': 13409,
 'purkiss': 19938,
 '15': 160,
 'civilians': 5047,
 'killed': 13918,
 'single': 22912,
 'us': 26313,
 'airstrike': 1294,
 'identified': 12380,
 'howard': 12178,
 'portnoy': 19199,
 'iranian': 13101,
 'jailed': 13287,
 'fictional': 9573,
 'unpublished': 26184,
 'story': 23951,
 'stoned': 23917,
 'death': 6658,
 'adultery': 1080,
 'nussbaum': 17407,
 'jackie': 13261,
 'mason': 15554,
 'hollywood': 11998,
 'would': 27594,
 'love': 14992,
 'trump': 25663,
 'bombed': 3494,
 'north': 17283,
 'korea': 14088,
 'lack': 14

In [27]:
len(after_trans.vocabulary_)

31782

In [28]:
TdmSpamData = after_trans.transform(news_data['content'])

In [29]:
TdmSpamData.shape
# TDM will act as my X values

(20800, 31782)

In [30]:
type(TdmSpamData)

scipy.sparse.csr.csr_matrix

In [31]:
TdmSpamData.toarray()[0::]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Spliting the data into Train and Test data

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
train_x , test_x , train_y , test_y = train_test_split(TdmSpamData, news_data.label, test_size=.2)

### Apply Naive Bayes

In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
nb_news_data = MultinomialNB()

In [36]:
nb_news_data.fit(train_x,train_y)

MultinomialNB()

In [37]:
pred = nb_news_data.predict(test_x)

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
tab = confusion_matrix(test_y,pred)
tab

array([[2049,   12],
       [ 130, 1969]], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(test_y,pred)*100

96.58653846153847

### Apply Decision Tree

In [42]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()                     # Default as gini

In [43]:
dt.fit(train_x,train_y)

DecisionTreeClassifier()

In [44]:
pred1 = dt.predict(test_x)
pred1

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [45]:
pred1.shape

(4160,)

In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,pred)

array([[2049,   12],
       [ 130, 1969]], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,pred) *100

96.58653846153847

### Apply Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier
rfc_trf = RandomForestClassifier()

In [49]:
rfc_trf.fit(train_x,train_y)

RandomForestClassifier()

In [50]:
pred2 = rfc_trf.predict(test_x)
pred2

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [51]:
from sklearn.metrics import confusion_matrix

tab_trf2 = confusion_matrix(test_y,pred2) 
tab_trf2

array([[2039,   22],
       [   6, 2093]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,pred2) *100

99.32692307692308

### Apply LogisticRegression 

In [53]:
from sklearn.linear_model import LogisticRegression 

In [54]:
log_cr= LogisticRegression()

In [55]:
log_cr.fit(train_x,train_y) 

LogisticRegression()

In [56]:
pred_test = log_cr.predict(test_x)
pred_test

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [57]:
from sklearn.metrics import confusion_matrix  # use this for matrix

In [58]:
tab_cr = confusion_matrix(test_y,pred_test)
tab_cr

array([[2025,   36],
       [   8, 2091]], dtype=int64)

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
accuracy_score(test_y,pred_test)*100

98.9423076923077

- We can see the Logistic regression model giving us good result